# Generated by Django 5.0.3 on 2024-04-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0002_alter_contact_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="subject",
            field=models.CharField(
                choices=[
                    ("service_request", "Service Request"),
                    ("collaboration", "Want to Work Together"),
                    ("sponsorship", "Sponsorship"),
                    ("complaint", "Complaint"),
                    ("none", "None Of These"),
                ],
                default="none",
                max_length=255,
            ),
        ),
    ]
