# Generated by Django 5.0.3 on 2024-06-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0003_alter_contact_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="name",
        ),
        migrations.AddField(
            model_name="contact",
            name="first_name",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="contact",
            name="last_name",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
