# Generated by Django 5.0.3 on 2024-06-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0004_remove_contact_name_contact_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="first_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="contact",
            name="last_name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
