# Generated by Django 5.0.3 on 2024-03-20 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="image",
        ),
    ]
