# Generated by Django 5.0.3 on 2024-04-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_remove_service_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="short_description",
            field=models.TextField(default="No short description provided."),
        ),
    ]
