# Generated by Django 5.0.3 on 2024-04-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_service_short_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="home_description",
            field=models.TextField(
                default="Brief overview for home page.",
                help_text="A concise description for the home page.",
            ),
        ),
    ]
