# Generated by Django 5.0.3 on 2024-04-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="author",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="parent",
        ),
        migrations.AddField(
            model_name="comment",
            name="author_name",
            field=models.CharField(default="Anonymous", max_length=100),
        ),
        migrations.AddField(
            model_name="comment",
            name="email",
            field=models.EmailField(default="no-email@example.com", max_length=254),
        ),
        migrations.AddField(
            model_name="comment",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
