# Generated by Django 5.0.3 on 2024-04-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_remove_comment_author_name_remove_comment_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("subscribed_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
