# Generated by Django 5.0.3 on 2024-04-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_emailsubscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailsubscription",
            name="subscribed_on",
        ),
        migrations.AddField(
            model_name="emailsubscription",
            name="nickname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
