# Generated by Django 5.0.3 on 2024-04-10 12:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_remove_emailsubscription_subscribed_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="nickname",
            field=models.CharField(
                blank=True,
                help_text="Nickname of the commenter",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="subscribe_to_updates",
            field=models.BooleanField(
                default=False,
                help_text="Whether the commenter wants to subscribe to updates",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="subscribed_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="emailsubscription",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="emailsubscription",
            name="subscribed_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
