# Generated by Django 5.0.3 on 2024-04-10 19:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_comment_nickname_comment_subscribe_to_updates_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailSubscription",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="nickname",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="subscribe_to_updates",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="subscribed_on",
        ),
    ]
