# Generated by Django 5.0.3 on 2024-04-15 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_remove_polloption_poll_remove_vote_poll_option_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="poll_option",
        ),
        migrations.DeleteModel(
            name="PollOption",
        ),
        migrations.DeleteModel(
            name="Vote",
        ),
    ]
